version: 4.4.0.0-extended.{build}

branches:
    only:
        - extended

skip_tags: true

assembly_info:
    patch: true
    file: AssemblyInfo.*
    assembly_version: "4.4.0.{build}"
    assembly_file_version: "{version}"
    assembly_informational_version: "{version}"

image: Visual Studio 2017

before_build:
    - ps: (Get-Content ElectronicObserver\Utility\SoftwareInformation.cs -Encoding UTF8).replace("<BUILD_VERSION>", "$env:APPVEYOR_BUILD_VERSION").replace("<BUILD_TIME>", (Get-Date -Format g)) | Set-Content ElectronicObserver\Utility\SoftwareInformation.cs -Encoding UTF8
    - mkdir output-template
    - mkdir output-template\Licenses
    - copy Licenses\*.* output-template\Licenses\
    - copy LICENSE output-template\LICENSE
    - mkdir output-template\Plugins
    - copy NUL output-template\Plugins\plugin_dir

build_script:
    - REM ================ net45 ================
    - git submodule update --init --recursive
    - nuget restore
    - msbuild ElectronicObserver.sln /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /p:Configuration=Release /m
    - REM ================ Package CEF flavors ================
    - xcopy /E /Y output-template output-net45-cef-full\
    - xcopy /E /Y output\ElectronicObserver output-net45-cef-full\
    - xcopy /E /Y output\Browser output-net45-cef-full\
    - xcopy /E output-net45-cef-full output-net45-cef\
    - rmdir /S /Q output-net45-cef\x86
    - rmdir /S /Q output-net45-cef\x64
    - REM ================ Package Gecko flavors ================
    - xcopy /E /Y output-template output-net45-gecko-full\
    - xcopy /E /Y output\ElectronicObserver output-net45-gecko-full\
    - xcopy /E /Y output\GeckoBrowser output-net45-gecko-full\
    - xcopy /E output-net45-gecko-full output-net45-gecko\
    - rmdir /S /Q output-net45-gecko\Firefox
    - REM ================ net40 ================
    - msbuild ElectronicObserver.sln /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /t:Clean
    - git checkout extended-net40
    - xcopy /E output-template output-net40\
    - git submodule sync
    - git submodule update --init --recursive
    - nuget restore
    - msbuild ElectronicObserver.sln /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
    - ps: if (!((git branch --contains $env:APPVEYOR_REPO_COMMIT) -like '*extended-net40')) { exit -1 }

artifacts:
    - path: output-net45-cef-full
      name: 74eoe-cef-full-$(APPVEYOR_BUILD_VERSION)
    - path: output-net45-cef
      name: 74eoe-cef-$(APPVEYOR_BUILD_VERSION)
    - path: output-net45-gecko-full
      name: 74eoe-gecko-full-$(APPVEYOR_BUILD_VERSION)
    - path: output-net45-gecko
      name: 74eoe-gecko-$(APPVEYOR_BUILD_VERSION)
    - path: output-net40
      name: 74eoe-net40-$(APPVEYOR_BUILD_VERSION)

deploy:
  provider: GitHub
  auth_token:
    secure: LRyrixQEgYtxLDVKSCkxkjmAzMS4gi+DABeBjkT1r9Tunat6Satr15XuwkCWwoY0
  artifact: /.*/
  on:
    branch: extended
